name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
      with:
        skip_adding_nixpkgs_channel: true
    - name: Install application
      run: nix-env -f default.nix -i
    - name: Run tests
      run: TUTORIAL_DIR=. run tests
